name: Setup Flutter and Dart Utilities
description: Sets up Flutter SDK and fetches reusable Dart tooling scripts

inputs:
  flutter_version:
    required: true
    description: The version of Flutter to install
  flutter_channel:
    required: true
    description: The Flutter release channel to use

runs:
  using: "composite"
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter_version }}
        channel: ${{ inputs.flutter_channel }}

    - name: Flutter Pub Get
      shell: bash
      run: flutter pub get

    - name: Fetch Dart Utility Scripts from reusable-repo-flutter
      shell: bash
      run: |
        mkdir -p .github/tool
        curl -sSL https://raw.githubusercontent.com/Rite-Technologies-23/reusable-repo-flutter/main/.github/tool/analyzer_to_html.dart -o .github/tool/analyzer_to_html.dart
        curl -sSL https://raw.githubusercontent.com/Rite-Technologies-23/reusable-repo-flutter/main/.github/tool/json_to_junit.dart -o .github/tool/json_to_junit.dart
        curl -sSL https://raw.githubusercontent.com/Rite-Technologies-23/reusable-repo-flutter/main/.github/tool/run_filtered_tests.dart -o .github/tool/run_filtered_tests.dart
