name: Setup Flutter and LCOV

description: Sets up Flutter and installs LCOV for coverage reporting

runs:
  using: "composite"
  steps:
    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}

    - name: Install Dependencies
      run: flutter pub get
      shell: bash

    - name: Install LCOV
      run: sudo apt-get update && sudo apt-get install -y lcov
      shell: bash
