name: "Flutter CI Reusable Workflow"

on:
  workflow_call:
    inputs:
      build_ios:
        required: false
        type: boolean
        default: false
    secrets:
      SONAR_TOKEN:
      CODACY_PROJECT_TOKEN:
env:
  FLUTTER_VERSION: ${{ vars.FLUTTER_VERSION }}
  FLUTTER_CHANNEL: ${{ vars.FLUTTER_CHANNEL }}

jobs:
  coverage:
    name: Generate Coverage
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Load environment variables from shell script
      - name: Load Environment Variables
        run: source .github/env.sh

      # Step 3: Set up Java environment (required for Flutter)
      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # Step 4: Set up Flutter and LCov using local action
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      # Step 5: Run Flutter tests with coverage and generate machine-readable output
      - name: Run Flutter Tests with Coverage and Machine Output
        run: |
          mkdir -p test-results
          flutter test --coverage --machine > test-results/results.json || true
          cat test-results/results.json

      # Step 6: Convert machine-readable test output to JUnit XML format
      - name: Convert to JUnit format
        run: |
          dart run .github/tool/json_to_junit.dart < test-results/results.json > test-results/test-report.xml || true
          cat test-results/test-report.xml

      # Step 7: Convert JUnit XML report to HTML
      - name: Convert JUnit XML to HTML
        uses: pl-strflt/junit-xml-to-html@v1
        with:
          mode: 'no-frames'
          input: 'test-results/test-report.xml'
          output: 'test-results/test-report.html'

      # Step 8: Analyze test results using custom Dart script (supports filtering/minor failure tolerance)
      - name: Analyze Test Results and Allow Minor Failures
        run: dart run .github/tool/run_filtered_tests.dart

      # Step 9: Upload the HTML test report as an artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Flutter-Test-Report
          path: test-results/test-report.html

      # Step 10: (Optional repeat) Run Flutter tests again to regenerate coverage
      - name: Run Flutter Tests with Coverage
        run: flutter test --coverage --machine > test-results/results.json || true

      # Step 11: Generate HTML report from LCOV coverage data
      - name: Generate HTML Coverage Report
        run: |
          mkdir -p coverage_report
          genhtml coverage/lcov.info \
            --output-directory coverage_report \
            --title "Flutter Test Coverage" \
            --show-details \
            --highlight \
            --legend

      # Step 12: Upload HTML coverage report as artifact
      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: Flutter-Coverage-Report
          path: coverage_report/

      # Step 13: Validate code coverage against a defined threshold
      - name: Check Coverage Threshold
        run: |
          total_coverage=$(lcov --summary coverage/lcov.info | grep -Po 'lines\.*: \K[0-9.]+(?=%)')
          echo "Total Coverage: $total_coverage%"
          result=$(echo "$total_coverage < ${{ vars.COVERAGE_THRESHOLD }}" | bc -l)
          if [ "$result" -eq 1 ]; then
            echo "Code coverage ($total_coverage%) is below threshold (${{ vars.COVERAGE_THRESHOLD }}%)."
            exit 1 
          else
            echo "Code coverage ($total_coverage%) meets the threshold." 
          fi

      # Step 14: Debug LCOV output if something goes wrong
      - name: Debug LCOV Output
        run: |
          ls -la coverage
          head coverage/lcov.info

      # Step 15: Ensure the coverage report file exists
      - name: Ensure Coverage Report is Ready
        run: |
          if [ ! -f coverage/lcov.info ]; then
            echo "lcov.info not found! Did coverage generation fail?"
            exit 1
          fi

      # Step 16: Preview lcov.info content and size
      - name: Confirm lcov.info is Populated
        run: |
          echo "Preview of lcov.info:"
          head -n 20 coverage/lcov.info
          echo "Size: $(du -h coverage/lcov.info)"

      # Step 17: Upload coverage data to Codacy
      - name: Upload Coverage to Codacy
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
            --language Dart \
            --coverage-reports coverage/lcov.info \
            --commit-uuid ${{ github.sha }} \
            --project-token ${{ secrets.CODACY_PROJECT_TOKEN }}

  build:
    name: Build App
    needs: coverage
    runs-on: ubuntu-latest

    steps:
      # Step 18: Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 19: Load environment variables from shell script
      - name: Load Environment Variables
        run: source .github/env.sh

      # Step 20: Set up Java for Flutter/Android build
      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # Step 21: Set up Flutter
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      # Step 22: Build debug APK for Android with ABI splits
      - name: Build Debug APK
        run: flutter build apk --split-per-abi

      # Step 23: Optionally build iOS app (no code signing)
      - name: Build iOS App
        if: ${{ vars.BUILD_IOS == 'true' }}
        run: flutter build ios --no-codesign

  sonarqube:
    name: SonarQube Scan
    needs: coverage
    runs-on: ubuntu-latest

    steps:
      # Step 24: Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 25: Run SonarQube static analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  codacy:
    name: Codacy Security Scan
    needs: coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      # Step 26: Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 27: Set up Flutter
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      # Step 28: Download and make Codacy CLI executable
      - name: Set up Codacy CLI
        run: |
          curl -Ls https://raw.githubusercontent.com/codacy/codacy-cli-v2/main/codacy-cli.sh \
            -o /tmp/codacy-cli-v2 && chmod +x /tmp/codacy-cli-v2

      # Step 29: Run Dart static code analysis using Codacy CLI
      - name: Run Codacy CLI Analysis
        run: |
          /tmp/codacy-cli-v2 analyze \
            --tool dartanalyzer \
            --format sarif \
            --output ./results.sarif

      # Step 30: Upload SARIF results to Codacy for reporting
      - name: Upload SARIF Results to Codacy
        run: |
          if [ -f ./results.sarif ]; then
            /tmp/codacy-cli-v2 upload \
              --sarif-path ./results.sarif \
              --commit-uuid ${{ github.sha }} \
              --project-token ${{ secrets.CODACY_PROJECT_TOKEN }}
          else
            echo "No SARIF file found, skipping upload"
          fi
